env:
  browser: true
  es2021: true
  jest/globals: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:jest/recommended"
  - "plugin:jest/style"
parser: babel-eslint
plugins:
  - jest
  - react
rules:
  import/extensions: [0, { js: "never", jsx: "never" }]
  import/prefer-default-export: 0
  function-paren-newline: ["error", "consistent"]

  react/forbid-prop-types: 0
  jsx-a11y/href-no-hash: 0

  jsx-a11y/anchor-is-valid: off

settings:
  import/ignore:
    - \.coffee$
    - \.(scss|less|css)$
  import/resolver:
    webpack:
      config: "config/webpack/development.js"
  react:
    createClass:
      createReactClass # Regex for Component Factory to use,
      # default to "createReactClass"
    pragma: React # Pragma to use, default to "React"
    version:
      detect
      # React version. "detect" automatically picks the version
      # you have installed.
      # You can also use `16.0`, `16.3`, etc, if you want to
      # override the detected value.
      # default to latest and warns if missing
      # It will default to "detect" in the future
    flowVersion: 0.53 # Flow Version
  propWrapperFunctions:
    # The names of any function used to wrap propTypes, e.g.
    # `forbidExtraProps`. If this isn't set, any propTypes wrapped in a
    # function will be skipped.
    forbidExtraProps:
      property:
        - freeze
        - object
        - Object
  linkComponents:
    - Hyperlink
    - { "name": "Link", "linkAttribute": "to" }
