env:
  browser: true
  es2021: true
  jest/globals: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:jest/recommended"
  - "plugin:jest/style"
parser:
  - babel-eslint
plugins:
  - jest
  - react
rules:
  import/extensions: [2, { js: "never", jsx: "never" }]
  function-paren-newline: ["error", "consistent"]

  react/forbid-prop-types: 0
  jsx-a11y/href-no-hash: 0

  jsx-a11y/anchor-is-valid: off
