require:
  - rubocop-rails
  - rubocop-rspec
Documentation:
  Enabled: false
AllCops:
  TargetRubyVersion: 3.0
  Includes:
    - Rakefile
    - config.ru
    - app/controllers/**
    - app/models/**
    - spec/**/**
  Excludes:
    - app/assets/**
    - db/**
    - config/**
    - script/**
    - bin/**

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Max: 105

Style/StringLiterals:
  EnforcedStyle: double_quotes
