language: ruby

rbenv:
  - 3.0.0

services:
  - postgresql

cache:
  bundler: true
  directories: node_modules
  yarn: true

gemfile: Gemfile

env:
  global:
    - RAILS_ENV=test
    - NODE_ENV=test
    - DRIVER=selenium_chrome
    - CHROME_BIN=/usr/bin/google-chrome
    - USE_COVERALLS=TRUE

before_install:
  - gem update --system
  - gem install bundler:2.2.7

install:
  - travis_retry nvm install 12
  - node -v
  - travis_retry npm i -g yarn
  - bundle
  - yarn

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U

script:
  - bundle exec rspec
  - yarn run test:client
