matrix:
  include:
    - language: ruby
      cache: bundler
      rbenv:
        - 2.7.0
      services:
        - postgresql
      before_install:
        - gem update --system
        - gem install bundler:2.1.2
      before_script:
        - cp config/database.yml.travis config/database.yml
        - psql -c 'create database travis_ci_test;' -U postgres
      script: "bundle exec rspec"

    - language: node_js
      node_js:
        - "15"
      script: "true"
