default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: clix_development

test:
  <<: *default
  database: clix_test

production:
  <<: *default
  database: clix_production
  username: clix
  password: <%= ENV['CLIX_DATABASE_PASSWORD'] %>
